### ISSUE TITLE
Add Details to GeoFence Detail View

### ISSUE THREAD

**Issue by jhbruhn** [alternaDev/georenting-android#6]

**Comment by jhbruhn** [comment]
Show statistics if own geofence, otherwise show other interesting Things

**Comment by olewehrmeyer** [comment]
I'm going to do some work on that. Please assign it to me or give me permission that I can do it myself :smile:

**Comment by jhbruhn** [comment]
I think we have to differentiate between fences owned by the user and fences owned by someone else:
Owned by the User:
- Expiry Countdown
- Total Earnings (@jhbruhn will implement this in the API)
- Total Visitors (@jhbruhn will implement this in the API)
- Initial Cost (@jhbruhn will implement this)
- (Current Value (Not sure about this. Would be possible but has to be thought about))
- Rent Multiplier
- ... (please make suggestions)

Owned by someone else:
- Expiry Countdown (?)
- Owner Name (@jhbruhn will implement this in the api)
- Owner Avatar
- ... (please make suggestions)

**Comment by jhbruhn** [comment]
I've added an Expiry Countdown for now, just for fun.

**Comment by jhbruhn** [comment]
zack feddich
